export const movies = [
    {   name: 'Iron Man',
        year: 2008,},
    {   name: 'The Incredible Hulk',
        year: 2008,},
    {   name: 'Iron Man 2',
        year: 2010,},
    {   name: 'Thor',
        year: 2011,},
    {   name: 'Captain America: The First Avenger',
        year: 2011,},
    {   name: 'Marvel\'s The Avengers',
        year: 2012,},
    {   name: 'Iron Man 3',
        year: 2013,},
    {   name: 'Thor: The Dark World',
        year: 2013,},
    {   name: 'Captain America: The Winter Soldier',
        year: 2014,},
    {   name: 'Guardians of the Galaxy',
        year: 2014,},
    {   name: 'Avengers: Age of Ultron',
        year: 2015,},
    {   name: 'Ant-Man',
        year: 2015,},
    {   name: 'Captain America: Civil War',
        year: 2016,},
    {   name: 'Doctor Strange',
        year: 2016,},
    {   name: 'Guardians of the Galaxy Vol. 2',
        year: 2017,},
    {   name: 'Spider-Man: Homecoming',
        year: 2017,},
    {   name: 'Thor: Ragnarok',
        year: 2017,},
    {   name: 'Black Panther',
        year: 2018,},
    {   name: 'Avengers: Infinity War',
        year: 2018,},
    {   name: 'Ant-Man and the Wasp',
        year: 2018,},
    {   name: 'Captain Marvel',
        year: 2019,},
    {   name: 'Avengers 4',
        year: 2019,},
    {   name: 'Spider-Man: Far From Home',
        year: 2019,},
];
